"""A deterministic stand-in for a chat model, so the app runs with no API key.

This is NOT a language model and does not pretend to be one. It implements the two
surfaces the agents actually call -- `.with_structured_output(Schema)` and
`.bind_tools(tools)` -- and answers with rule-based output derived from the same
context a real model would receive.

What that buys: `docker compose up` gives a working system with every endpoint,
the event bus, the LangGraph state machines, the tool-calling loop, and the
database writes all exercised end to end, at zero cost and with no network. What
it does not buy: any judgment. Scores come from the weights below, not from
reading the deal. Switch LLM_PROVIDER to `anthropic` for that.
"""

import json
import re
from typing import Any

from langchain_core.messages import AIMessage, ToolMessage

SENIOR_TITLES = (
    "chief", "ceo", "cto", "cfo", "coo", "vp", "vice president",
    "head of", "director", "founder", "president", "partner", "owner",
)
MID_TITLES = ("manager", "lead", "principal", "senior")

STAGE_POINTS = {
    "new": 0,
    "qualified": 5,
    "proposal": 10,
    "negotiation": 15,
    "won": 20,
    "lost": 0,
}


def _human_text(messages: list) -> str:
    """Pull the user-supplied half of the prompt, whatever shape it arrives in."""
    for message in reversed(messages):
        if isinstance(message, tuple) and message[0] == "human":
            return str(message[1])
        role = getattr(message, "type", None)
        if role == "human":
            return str(message.content)
    return ""


def _context(messages: list) -> dict:
    try:
        return json.loads(_human_text(messages))
    except (ValueError, TypeError):
        return {}


def _title_points(title: str | None) -> tuple[int, str]:
    if not title:
        return 0, "no named contact"
    lowered = title.lower()
    if any(word in lowered for word in SENIOR_TITLES):
        return 25, f"a senior champion ({title})"
    if any(word in lowered for word in MID_TITLES):
        return 12, f"a mid-level contact ({title})"
    return 6, f"an individual contributor contact ({title})"


def _score_deal(context: dict) -> tuple[float, str, str]:
    deal = context.get("deal") or {}
    company = context.get("company") or {}
    contact = context.get("contact") or {}
    history = context.get("activity_history") or []

    value = float(deal.get("value") or 0)
    value_points = min(40.0, value / 3000)
    title_points, title_phrase = _title_points(contact.get("title"))
    activity_points = min(20, 5 * len(history))
    industry_points = 5 if company.get("industry") else 0
    stage_points = STAGE_POINTS.get(deal.get("stage", ""), 0)

    score = min(
        100.0,
        value_points + title_points + activity_points + industry_points + stage_points,
    )
    priority = "high" if score >= 80 else "medium" if score >= 50 else "low"

    activity_phrase = (
        f"{len(history)} logged touchpoint{'s' if len(history) != 1 else ''}"
        if history
        else "no logged activity"
    )
    reasoning = (
        f"Scored {score:.0f}/100. Value of ${value:,.0f} at the "
        f"'{deal.get('stage', 'unknown')}' stage, with {title_phrase} and "
        f"{activity_phrase}. "
        f"{'Worth prioritising this week.' if priority == 'high' else 'Keep it warm; the strongest signal here is not yet value plus engagement.' if priority == 'medium' else 'Low signal - qualify further before investing rep time.'} "
        f"(Generated by the deterministic stub scorer, not a language model.)"
    )
    return score, priority, reasoning


def _draft_message(context: dict) -> tuple[str, str]:
    deal = context.get("deal") or {}
    contact = context.get("contact") or {}
    history = context.get("activity_history") or []

    name = deal.get("name", "our conversation")
    first_name = (contact.get("name") or "there").split()[0]
    stage = deal.get("stage", "new")

    if history:
        last = history[0]
        anchor = f"Following up on {last.get('subject') or last.get('type', 'our last exchange')}"
    else:
        anchor = "Following up since we haven't connected recently"

    if stage in ("proposal", "negotiation"):
        ask = "Are you free for 20 minutes this week to walk through the remaining open points?"
    else:
        ask = "Would it be useful to set up a short call to see whether this is worth exploring further?"

    subject = f"Following up on {name}"
    body = (
        f"Hi {first_name},\n\n"
        f"{anchor}. I wanted to check in on where things stand with {name}.\n\n"
        f"{ask}\n\n"
        f"Best,\n\n"
        f"---\nDraft generated by the deterministic stub provider for review. "
        f"Set LLM_PROVIDER=anthropic for a model-written draft."
    )
    return subject, body


class _StubStructured:
    """Implements the `.invoke()` half of `with_structured_output(Schema)`."""

    def __init__(self, schema: Any):
        self._schema = schema

    def invoke(self, messages: list) -> Any:
        fields = set(getattr(self._schema, "model_fields", {}))
        context = _context(messages)

        if {"score", "priority", "reasoning"} <= fields:
            score, priority, reasoning = _score_deal(context)
            return self._schema(score=score, priority=priority, reasoning=reasoning)

        if {"subject", "body"} <= fields:
            subject, body = _draft_message(context)
            return self._schema(subject=subject, body=body)

        raise NotImplementedError(
            f"Stub provider has no rule for schema {self._schema.__name__!r}. "
            f"Add one in app/agents/stub.py or set LLM_PROVIDER=anthropic."
        )


class _StubToolCaller:
    """Implements the `.invoke()` half of `bind_tools(tools)`.

    Runs one deterministic tool call, then summarises whatever the tool returned.
    Tool selection is keyword routing -- crude, but it exercises the real
    conditional edge, the real ToolNode, and the real RBAC-scoped queries.
    """

    def __init__(self, tools: list):
        self._tool_names = {getattr(t, "name", str(t)) for t in tools}

    def _pick(self, question: str) -> tuple[str, dict]:
        q = question.lower()

        if any(word in q for word in ("contact", "who at", "who is", "champion")):
            match = re.search(r"\bat ([A-Z][\w& ]+)", question)
            args = {"company_name": match.group(1).strip()} if match else {}
            return "query_contacts", args

        if any(
            word in q
            for word in ("how many", "count", "total", "breakdown", "by stage", "by priority", "sum", "pipeline")
        ):
            group_by = "priority" if "priority" in q else "stage"
            return "aggregate_stats", {"group_by": group_by}

        args: dict = {}
        for stage in STAGE_POINTS:
            if stage in q:
                args["stage"] = stage
                break
        for priority in ("high", "medium", "low"):
            if f"{priority} priority" in q or f"{priority}-priority" in q:
                args["priority"] = priority
                break
        return "query_deals", args

    @staticmethod
    def _summarise(results: list[ToolMessage]) -> str:
        lines = []
        for message in results:
            try:
                rows = json.loads(message.content)
            except (ValueError, TypeError):
                rows = message.content
            if isinstance(rows, list) and rows:
                for row in rows[:10]:
                    lines.append(
                        "- " + ", ".join(f"{k}: {v}" for k, v in row.items() if v is not None)
                    )
            elif isinstance(rows, list):
                lines.append("- (no matching records)")
            else:
                lines.append(f"- {rows}")
        body = "\n".join(lines) if lines else "No results returned."
        return (
            f"{body}\n\n"
            "(Rows are live, RBAC-scoped query results; the summary around them is "
            "templated by the stub provider rather than written by a model.)"
        )

    def invoke(self, messages: list) -> AIMessage:
        tool_results = [m for m in messages if isinstance(m, ToolMessage)]
        if tool_results:
            return AIMessage(content=self._summarise(tool_results))

        name, args = self._pick(_human_text(messages))
        if name not in self._tool_names:
            name, args = "query_deals", {}
        return AIMessage(
            content="",
            tool_calls=[{"name": name, "args": args, "id": f"stub-{name}"}],
        )


class StubChatModel:
    """Drop-in stand-in for ChatAnthropic across every agent in the app."""

    def __init__(self, agent_name: str):
        self.agent_name = agent_name

    def with_structured_output(self, schema: Any) -> _StubStructured:
        return _StubStructured(schema)

    def bind_tools(self, tools: list) -> _StubToolCaller:
        return _StubToolCaller(tools)

    def invoke(self, messages: list) -> AIMessage:
        return AIMessage(content="Stub provider: no model configured.")
